[package]
name = "s2_lib"
version = "0.1.0"
edition = "2021"

[features]
default = ["fma"]
fma = []

[dependencies]
anyhow = "1.0.69"
fxhash = "0.2.1"
log = "0.4.17"
rand = "0.8.5"
rand_pcg = "0.3.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sleef = "0.2.0"
