[workspace]
resolver = "2"
members = [
  "components/*",
]
default-members = [
  "components/s2_bin",
]

[patch."https://github.com/robbert-vdh/nih-plug.git"]
nih_plug_xtask = { version = "0.1.0", path = "../nih-plug/nih_plug_xtask" }
