[profile.dev]
opt-level = 1

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=haswell", "-C", "target-feature=+sse3,+avx,+avx2,+fma"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=haswell", "-C", "target-feature=+sse3,+avx,+avx2,+fma"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=haswell", "-C", "target-feature=+sse3,+avx,+avx2,+fma"]

[alias]
xtask = "run -p xtask --release --"
