[profile.dev]
opt-level = 1

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=skylake-avx512", "--emit", "asm"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-cpu=skylake-avx512", "--emit", "asm"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=skylake-avx512", "--emit", "asm"]

[alias]
xtask = "run -p xtask --release --"
